spring.application.name=Electricity Bill Generator

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/elec_bill
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secret=8qUSQfJK3ogqiv-Uh83hIP9hCZmac30KpdWpXihxmX-OUTBe9I_6qufhGWBUkWMpz28QwgIHg_0C4pzbAjykyA
jwt.expiration=86400

# Logging
logging.level.com.project.electricitybillgenerator=INFO
logging.level.org.springframework.security=DEBUG

# Scheduling Configuration
spring.task.scheduling.pool.size=2
spring.task.scheduling.thread-name-prefix=billing-scheduler-